### Retrieve token
POST http://metabase.cometmedias.com/api/session
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### Get queries
GET https://metabase.cometmedias.com/api/collection/11/items
'X-Metabase-Session: '

### Get contacts
POST https://metabase.cometmedias.com/api/card/9/query
'X-Metabase-Session: '
